version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: aman
      POSTGRES_PASSWORD: aman
      POSTGRES_DB: ecom
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
